#! /bin/bash
answers=$'Lock\nShutdown now\nSleep\nReboot'
answer=$(echo "$answers" | rofi -dmenu -i -p "action menu")

if [ "$answer" == "Shutdown now" ]; then
	shutdown -h 0
elif [ "$answer" == "Lock" ]; then
	i3lock-fancy
elif [ "$answer" == "Reboot" ]; then
	reboot
elif [ "$answer" == "Sleep" ]; then
	systemctl suspend
fi
