#! /bin/bash
answers=$'Shutdown now\nReboot\nExtend left\nExtend Right\nCopy'
answer=$(echo "$answers" | rofi -dmenu -i -p "action menu")

if [ "$answer" == "Shutdown now" ]; then
	shutdown -h 0
elif [ "$answer" == "Reboot" ]; then
	reboot
elif [ "$answer" == "Extend Left" ]; then
	xrandr --output VGA-1 --left-of LVDS-1 --auto
elif [ "$answer" == "Extend Right" ]; then
	xrandr --output VGA-1 --right-of LVDS-1 --auto
elif [ "$answer" == "Copy" ]; then
	xrandr --output VGA-1 --auto
fi
